In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [10]:
# one hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[3268, 702, 8011, 8607], [3268, 702, 8011, 9164], [3268, 5191, 8011, 3604], [2549, 4683, 2239, 4921, 1565], [2549, 4683, 2239, 4921, 8389], [2138, 3268, 5087, 8011, 41], [5246, 6903, 7154, 4921]]


In [11]:
## word Embedding Representation 

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential 

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3268  702 8011 8607]
 [   0    0    0    0 3268  702 8011 9164]
 [   0    0    0    0 3268 5191 8011 3604]
 [   0    0    0 2549 4683 2239 4921 1565]
 [   0    0    0 2549 4683 2239 4921 8389]
 [   0    0    0 2138 3268 5087 8011   41]
 [   0    0    0    0 5246 6903 7154 4921]]


In [14]:
## feature representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\GitHub-Repos\Simple RNN\Senv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step


array([[[-3.90715599e-02, -4.17453274e-02, -3.01750898e-02,
          2.63446569e-03, -8.91502947e-03, -2.00476181e-02,
         -4.30295616e-03,  1.61920823e-02, -2.27101929e-02,
         -2.43501663e-02],
        [-3.90715599e-02, -4.17453274e-02, -3.01750898e-02,
          2.63446569e-03, -8.91502947e-03, -2.00476181e-02,
         -4.30295616e-03,  1.61920823e-02, -2.27101929e-02,
         -2.43501663e-02],
        [-3.90715599e-02, -4.17453274e-02, -3.01750898e-02,
          2.63446569e-03, -8.91502947e-03, -2.00476181e-02,
         -4.30295616e-03,  1.61920823e-02, -2.27101929e-02,
         -2.43501663e-02],
        [-3.90715599e-02, -4.17453274e-02, -3.01750898e-02,
          2.63446569e-03, -8.91502947e-03, -2.00476181e-02,
         -4.30295616e-03,  1.61920823e-02, -2.27101929e-02,
         -2.43501663e-02],
        [ 4.55759428e-02, -2.88632866e-02,  2.44158022e-02,
         -2.33431458e-02, -1.11765489e-02, -4.68395725e-02,
          1.43139698e-02,  3.44656445e-02,  5.852341

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 3268,  702, 8011, 8607], dtype=int32)

In [19]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>

In [20]:
## Save model file
model.save('simple_rnn_imdb.h5')